name: Fetch JSON Report

permissions:
  contents: write

on:
  schedule:
    # Her 5 dakikada bir çalışması için:
    - cron: "*/5 * * * *"
  workflow_dispatch: # Manuel çalıştırma butonu

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu çek
        uses: actions/checkout@v4

      - name: JSON API'den veriyi al
        run: |
          # API'den veriyi çek ve report.json olarak kaydet
          curl -s https://falzer6.peuplade.com.tr/report -o report.json

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add report.json
          # Eğer dosyada değişiklik yoksa hata vermemesi için || echo kullanıyoruz
          git commit -m "API report güncellendi: $(date +'%Y-%m-%d %H:%M:%S')" || echo "Degisiklik yok"
          git push
